import {image} from '../utils';
export const appImages: image.imagesFace = {
  chatIconBlack: require('../assets/images/chatIconBlack.png'),
  commentsFilledWhite: require('../assets/images/commentsFilledWhite.png'),
  gameBlack: require('../assets/images/gameBlack.png'),
  gameWhite: require('../assets/images/gameWhite.png'),
  heartRedFilled: require('../assets/images/heartRedFilled.png'),
  heartWhite: require('../assets/images/heartWhite.png'),
  homeBlue: require('../assets/images/homeBlue.png'),
  homeWhite: require('../assets/images/homeWhite.png'),
  mediaBlack: require('../assets/images/mediaBlack.png'),
  mediaFilledBlack: require('../assets/images/mediaFilledBlack.png'),
  mediaFilledWhite: require('../assets/images/mediaFilledWhite.png'),
  notificationBlack: require('../assets/images/notificationBlack.png'),
  reportsBlack: require('../assets/images/reportsBlack.png'),
  reportsWhite: require('../assets/images/reportsWhite.png'),
  searchBlack: require('../assets/images/searchBlack.png'),
  threeDotsFilledWhite: require('../assets/images/threeDotsFilledWhite.png'),
  user: require('../assets/images/user.png'),
  videoFilledWhite: require('../assets/images/videoFilledWhite.png'),
  videoWhite: require('../assets/images/videoWhite.png'),
  mainLogo: require('../assets/images/logo.png'),
  arrowRight: require('../assets/images/arrowRight.png'),
  diamonds: require('../assets/images/diamonds.png'),
};
